# TCL File Generated by Component Editor 18.1
# Mon Sep 08 04:05:05 JST 2025
# DO NOT MODIFY


# 
# qcnn_ip "qcnn ip" v1.0
#  2025.09.08.04:05:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module qcnn_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME qcnn_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "qcnn ip"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL qcnn_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file qcnn_top.v VERILOG PATH ../src/qcnn_top.v
add_fileset_file AdderTree.sv SYSTEM_VERILOG PATH ../src/AdderTree.sv
add_fileset_file Argmax10.v VERILOG PATH ../src/Argmax10.v
add_fileset_file DPUconv1ch0.v VERILOG PATH ../src/DPUconv1ch0.v
add_fileset_file DPUconv1ch1.v VERILOG PATH ../src/DPUconv1ch1.v
add_fileset_file DPUconv1ch2.v VERILOG PATH ../src/DPUconv1ch2.v
add_fileset_file DPUconv1ch3.v VERILOG PATH ../src/DPUconv1ch3.v
add_fileset_file DPUconv2ch0.v VERILOG PATH ../src/DPUconv2ch0.v
add_fileset_file DPUconv2ch1.v VERILOG PATH ../src/DPUconv2ch1.v
add_fileset_file DPUconv2ch2.v VERILOG PATH ../src/DPUconv2ch2.v
add_fileset_file DPUconv2ch3.v VERILOG PATH ../src/DPUconv2ch3.v
add_fileset_file DPUconv2ch4.v VERILOG PATH ../src/DPUconv2ch4.v
add_fileset_file DPUconv2ch5.v VERILOG PATH ../src/DPUconv2ch5.v
add_fileset_file DPUconv2ch6.v VERILOG PATH ../src/DPUconv2ch6.v
add_fileset_file DPUconv2ch7.v VERILOG PATH ../src/DPUconv2ch7.v
add_fileset_file DPUfc1ch0.v VERILOG PATH ../src/DPUfc1ch0.v
add_fileset_file DPUfc1ch1.v VERILOG PATH ../src/DPUfc1ch1.v
add_fileset_file DPUfc1ch2.v VERILOG PATH ../src/DPUfc1ch2.v
add_fileset_file DPUfc1ch3.v VERILOG PATH ../src/DPUfc1ch3.v
add_fileset_file DPUfc1ch4.v VERILOG PATH ../src/DPUfc1ch4.v
add_fileset_file DPUfc1ch5.v VERILOG PATH ../src/DPUfc1ch5.v
add_fileset_file DPUfc1ch6.v VERILOG PATH ../src/DPUfc1ch6.v
add_fileset_file DPUfc1ch7.v VERILOG PATH ../src/DPUfc1ch7.v
add_fileset_file DPUfc1ch8.v VERILOG PATH ../src/DPUfc1ch8.v
add_fileset_file DPUfc1ch9.v VERILOG PATH ../src/DPUfc1ch9.v
add_fileset_file LineBuffer_2x2_even.v VERILOG PATH ../src/LineBuffer_2x2_even.v
add_fileset_file LineBuffer_2x2_odd.v VERILOG PATH ../src/LineBuffer_2x2_odd.v
add_fileset_file LineBuffer_3x3.v VERILOG PATH ../src/LineBuffer_3x3.v
add_fileset_file MaxPool2x2.v VERILOG PATH ../src/MaxPool2x2.v
add_fileset_file PipelineDelay.v VERILOG PATH ../src/PipelineDelay.v
add_fileset_file PostConv.v VERILOG PATH ../src/PostConv.v
add_fileset_file PostFC.v VERILOG PATH ../src/PostFC.v
add_fileset_file qcnn_ip.v VERILOG PATH ../src/qcnn_ip.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_1
# 
add_interface avalon_slave_1 avalon end
set_interface_property avalon_slave_1 addressUnits WORDS
set_interface_property avalon_slave_1 associatedClock clock
set_interface_property avalon_slave_1 associatedReset reset
set_interface_property avalon_slave_1 bitsPerSymbol 8
set_interface_property avalon_slave_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_1 burstcountUnits WORDS
set_interface_property avalon_slave_1 explicitAddressSpan 16
set_interface_property avalon_slave_1 holdTime 0
set_interface_property avalon_slave_1 linewrapBursts false
set_interface_property avalon_slave_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_1 readLatency 0
set_interface_property avalon_slave_1 readWaitStates 0
set_interface_property avalon_slave_1 readWaitTime 0
set_interface_property avalon_slave_1 setupTime 0
set_interface_property avalon_slave_1 timingUnits Cycles
set_interface_property avalon_slave_1 writeWaitTime 0
set_interface_property avalon_slave_1 ENABLED true
set_interface_property avalon_slave_1 EXPORT_OF ""
set_interface_property avalon_slave_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_1 address address Input 3
add_interface_port avalon_slave_1 byteenable byteenable Input 4
add_interface_port avalon_slave_1 chipselect chipselect Input 1
add_interface_port avalon_slave_1 read read Input 1
add_interface_port avalon_slave_1 readdata readdata Output 32
add_interface_port avalon_slave_1 waitrequest waitrequest Output 1
add_interface_port avalon_slave_1 write write Input 1
add_interface_port avalon_slave_1 writedata writedata Input 32
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_1 embeddedsw.configuration.isPrintableDevice 0

