# TCL File Generated by Component Editor 18.1
# Mon Sep 08 06:02:29 JST 2025
# DO NOT MODIFY


# 
# st2mm_qcnn_ip "Stream-to-Memory-Mapped bridge for QCNN IP" v1.0
#  2025.09.08.06:02:29
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module st2mm_qcnn_ip
# 
set_module_property DESCRIPTION ""
set_module_property NAME st2mm_qcnn_ip
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Stream-to-Memory-Mapped bridge for QCNN IP"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL st2mm_qcnn_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file st2mm_qcnn_ip.sv SYSTEM_VERILOG PATH ../src/st2mm_qcnn_ip.sv TOP_LEVEL_FILE
add_fileset_file qcnn_top.v VERILOG PATH ../src/qcnn_top.v
add_fileset_file AdderTree.sv SYSTEM_VERILOG PATH ../src/AdderTree.sv
add_fileset_file Argmax10.v VERILOG PATH ../src/Argmax10.v
add_fileset_file DPUconv1ch0.v VERILOG PATH ../src/DPUconv1ch0.v
add_fileset_file DPUconv1ch1.v VERILOG PATH ../src/DPUconv1ch1.v
add_fileset_file DPUconv1ch2.v VERILOG PATH ../src/DPUconv1ch2.v
add_fileset_file DPUconv1ch3.v VERILOG PATH ../src/DPUconv1ch3.v
add_fileset_file DPUconv2ch0.v VERILOG PATH ../src/DPUconv2ch0.v
add_fileset_file DPUconv2ch1.v VERILOG PATH ../src/DPUconv2ch1.v
add_fileset_file DPUconv2ch2.v VERILOG PATH ../src/DPUconv2ch2.v
add_fileset_file DPUconv2ch3.v VERILOG PATH ../src/DPUconv2ch3.v
add_fileset_file DPUconv2ch4.v VERILOG PATH ../src/DPUconv2ch4.v
add_fileset_file DPUconv2ch5.v VERILOG PATH ../src/DPUconv2ch5.v
add_fileset_file DPUconv2ch6.v VERILOG PATH ../src/DPUconv2ch6.v
add_fileset_file DPUconv2ch7.v VERILOG PATH ../src/DPUconv2ch7.v
add_fileset_file DPUfc1ch0.v VERILOG PATH ../src/DPUfc1ch0.v
add_fileset_file DPUfc1ch1.v VERILOG PATH ../src/DPUfc1ch1.v
add_fileset_file DPUfc1ch2.v VERILOG PATH ../src/DPUfc1ch2.v
add_fileset_file DPUfc1ch3.v VERILOG PATH ../src/DPUfc1ch3.v
add_fileset_file DPUfc1ch4.v VERILOG PATH ../src/DPUfc1ch4.v
add_fileset_file DPUfc1ch5.v VERILOG PATH ../src/DPUfc1ch5.v
add_fileset_file DPUfc1ch6.v VERILOG PATH ../src/DPUfc1ch6.v
add_fileset_file DPUfc1ch7.v VERILOG PATH ../src/DPUfc1ch7.v
add_fileset_file DPUfc1ch8.v VERILOG PATH ../src/DPUfc1ch8.v
add_fileset_file DPUfc1ch9.v VERILOG PATH ../src/DPUfc1ch9.v
add_fileset_file LineBuffer_2x2_even.v VERILOG PATH ../src/LineBuffer_2x2_even.v
add_fileset_file LineBuffer_2x2_odd.v VERILOG PATH ../src/LineBuffer_2x2_odd.v
add_fileset_file LineBuffer_3x3.v VERILOG PATH ../src/LineBuffer_3x3.v
add_fileset_file MaxPool2x2.v VERILOG PATH ../src/MaxPool2x2.v
add_fileset_file PipelineDelay.v VERILOG PATH ../src/PipelineDelay.v
add_fileset_file PostConv.v VERILOG PATH ../src/PostConv.v
add_fileset_file PostFC.v VERILOG PATH ../src/PostFC.v


# 
# parameters
# 
add_parameter IMG_W INTEGER 28
set_parameter_property IMG_W DEFAULT_VALUE 28
set_parameter_property IMG_W DISPLAY_NAME IMG_W
set_parameter_property IMG_W TYPE INTEGER
set_parameter_property IMG_W UNITS None
set_parameter_property IMG_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IMG_W HDL_PARAMETER true
add_parameter IMG_H INTEGER 26
set_parameter_property IMG_H DEFAULT_VALUE 26
set_parameter_property IMG_H DISPLAY_NAME IMG_H
set_parameter_property IMG_H TYPE INTEGER
set_parameter_property IMG_H UNITS None
set_parameter_property IMG_H ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IMG_H HDL_PARAMETER true
add_parameter SINK_FORMAT INTEGER 0
set_parameter_property SINK_FORMAT DEFAULT_VALUE 0
set_parameter_property SINK_FORMAT DISPLAY_NAME SINK_FORMAT
set_parameter_property SINK_FORMAT TYPE INTEGER
set_parameter_property SINK_FORMAT UNITS None
set_parameter_property SINK_FORMAT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SINK_FORMAT HDL_PARAMETER true
add_parameter X0 INTEGER 128
set_parameter_property X0 DEFAULT_VALUE 128
set_parameter_property X0 DISPLAY_NAME X0
set_parameter_property X0 TYPE INTEGER
set_parameter_property X0 UNITS None
set_parameter_property X0 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property X0 HDL_PARAMETER true
add_parameter SCALE_NUM INTEGER 1
set_parameter_property SCALE_NUM DEFAULT_VALUE 1
set_parameter_property SCALE_NUM DISPLAY_NAME SCALE_NUM
set_parameter_property SCALE_NUM TYPE INTEGER
set_parameter_property SCALE_NUM UNITS None
set_parameter_property SCALE_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SCALE_NUM HDL_PARAMETER true
add_parameter SHIFT INTEGER 0
set_parameter_property SHIFT DEFAULT_VALUE 0
set_parameter_property SHIFT DISPLAY_NAME SHIFT
set_parameter_property SHIFT TYPE INTEGER
set_parameter_property SHIFT UNITS None
set_parameter_property SHIFT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SHIFT HDL_PARAMETER true
add_parameter Y0 INTEGER 0
set_parameter_property Y0 DEFAULT_VALUE 0
set_parameter_property Y0 DISPLAY_NAME Y0
set_parameter_property Y0 TYPE INTEGER
set_parameter_property Y0 UNITS None
set_parameter_property Y0 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property Y0 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink sink_data data Input 8
add_interface_port avalon_streaming_sink sink_valid valid Input 1
add_interface_port avalon_streaming_sink sink_ready ready Output 1
add_interface_port avalon_streaming_sink sink_sop startofpacket Input 1
add_interface_port avalon_streaming_sink sink_eop endofpacket Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave address address Input 3
add_interface_port avalon_slave byteenable byteenable Input 4
add_interface_port avalon_slave chipselect chipselect Input 1
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave readdata readdata Output 32
add_interface_port avalon_slave waitrequest waitrequest Output 1
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

