module vga_qcnn (
input CLOCK_50,
input [17:0] SW,
output [7:0] HEX0,
output VGA_BLANK_N,
output [7:0] VGA_B,
output VGA_CLK,
output [7:0] VGA_G,
output VGA_HS,
output [7:0] VGA_R,
output VGA_SYNC_N,
output VGA_VS,
output [12:0] DRAM_ADDR,
output [1:0] DRAM_BA,
output DRAM_CAS_N,
output DRAM_CKE,
output DRAM_CLK,
output DRAM_CS_N,
inout [31:0] DRAM_DQ,
output [3:0] DRAM_DQM,
output DRAM_RAS_N,
output DRAM_WE_N,
output [19:0] SRAM_ADDR,
output SRAM_CE_N,
inout [15:0] SRAM_DQ,
output SRAM_LB_N,
output SRAM_OE_N,
output SRAM_UB_N,
output SRAM_WE_N
);
assign VGA_BLANK_N = 1'b1;
assign VGA_SYNC_N = 1'b0;
vga_qcnn_system u0 (
.clk_clk (CLOCK_50),
 .reset_reset_n (1'b1),
 .sdram_ext_addr (DRAM_ADDR),
 .sdram_ext_ba (DRAM_BA),
 .sdram_ext_cas_n (DRAM_CAS_N),
 .sdram_ext_cke (DRAM_CKE),
 .sdram_ext_cs_n (DRAM_CS_N),
 .sdram_ext_dq (DRAM_DQ),
  .sdram_ext_dqm (DRAM_DQM),
 .sdram_ext_ras_n (DRAM_RAS_N),
 .sdram_ext_we_n (DRAM_WE_N),
 .sdram_clk_clk (DRAM_CLK),
.hex0_ext_export(HEX0),
.sw_ext_export (SW),
.sram_ext_DQ (SRAM_DQ),
 .sram_ext_ADDR (SRAM_ADDR),
 .sram_ext_LB_N (SRAM_LB_N),
 .sram_ext_UB_N (SRAM_UB_N),
 .sram_ext_CE_N (SRAM_CE_N),
 .sram_ext_OE_N (SRAM_OE_N),
 .sram_ext_WE_N (SRAM_WE_N),
 .vga_ext_CLK (VGA_CLK),
 .vga_ext_HS (VGA_HS),
 .vga_ext_VS (VGA_VS),
 .vga_ext_BLANK (),
 .vga_ext_SYNC (),
 .vga_ext_R (VGA_R),
 .vga_ext_G (VGA_G),
 .vga_ext_B (VGA_B)
);
endmodule